version: '3'
services:
  ord-server:
    image: ord-server
    container_name: ord-server
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /ordinals:/ordinals:rw
      - /home/bitcoin/.bitcoin:/root/.bitcoin
    environment:
      RPC_HOST: "127.0.0.1"
      RPC_PORT: "8332"
      COOKIE_FILE: "/root/.bitcoin/.cookie"
      DATA_DIR: "/ordinals/index-data"
      HTTP_PORT: "8080"
      RUST_LOG: "INFO"
      RUST_BACKTRACE: "FULL"
    network_mode: host
    expose:
      - "8080"