version: '3'
services:
  ord:
    image: ord
    container_name: ord
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
#     You can use any of these paths to store the index data on your host machine (or any other path you like) 
#     Default paths for each os are listed below - just comment / uncomment as needed
      - ~/.local/share/ord:/ordinals:rw # linux
#      - /roaming/ord:/ordinals:rw # windows
#      - ~/Library/Application Support/ord:/ordinals:rw # OS X
      - ~/.bitcoin:/root/.bitcoin
    environment:
      RPC_HOST: "127.0.0.1"
      RPC_PORT: "8332"
      COOKIE_FILE: "/root/.bitcoin/.cookie"
      DATA_DIR: "/ordinals/index-data"
      HTTP_PORT: "8080"
      RUST_LOG: "INFO"
      RUST_BACKTRACE: "FULL"
    network_mode: host
    expose:
      - "8080"